// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: note.proto

package note_v1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoteINfo_Role int32

const (
	NoteINfo_role_unspecified NoteINfo_Role = 0
	NoteINfo_user             NoteINfo_Role = 1
	NoteINfo_admin            NoteINfo_Role = 2
)

// Enum value maps for NoteINfo_Role.
var (
	NoteINfo_Role_name = map[int32]string{
		0: "role_unspecified",
		1: "user",
		2: "admin",
	}
	NoteINfo_Role_value = map[string]int32{
		"role_unspecified": 0,
		"user":             1,
		"admin":            2,
	}
)

func (x NoteINfo_Role) Enum() *NoteINfo_Role {
	p := new(NoteINfo_Role)
	*p = x
	return p
}

func (x NoteINfo_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoteINfo_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_note_proto_enumTypes[0].Descriptor()
}

func (NoteINfo_Role) Type() protoreflect.EnumType {
	return &file_note_proto_enumTypes[0]
}

func (x NoteINfo_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoteINfo_Role.Descriptor instead.
func (NoteINfo_Role) EnumDescriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{0, 0}
}

type NoteINfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password         string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PasswordCoonfirm string                 `protobuf:"bytes,4,opt,name=password_coonfirm,json=passwordCoonfirm,proto3" json:"password_coonfirm,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NoteINfo) Reset() {
	*x = NoteINfo{}
	mi := &file_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteINfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteINfo) ProtoMessage() {}

func (x *NoteINfo) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteINfo.ProtoReflect.Descriptor instead.
func (*NoteINfo) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{0}
}

func (x *NoteINfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoteINfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NoteINfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NoteINfo) GetPasswordCoonfirm() string {
	if x != nil {
		return x.PasswordCoonfirm
	}
	return ""
}

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *NoteINfo              `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{1}
}

func (x *Note) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Note) GetInfo() *NoteINfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Note) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *NoteINfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetInfo() *NoteINfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponce) Reset() {
	*x = CreateResponce{}
	mi := &file_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponce) ProtoMessage() {}

func (x *CreateResponce) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponce.ProtoReflect.Descriptor instead.
func (*CreateResponce) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponce) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_note_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          NoteINfo_Role          `protobuf:"varint,4,opt,name=role,proto3,enum=note_v1.NoteINfo_Role" json:"role,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponce) Reset() {
	*x = GetResponce{}
	mi := &file_note_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponce) ProtoMessage() {}

func (x *GetResponce) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponce.ProtoReflect.Descriptor instead.
func (*GetResponce) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponce) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetResponce) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetResponce) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetResponce) GetRole() NoteINfo_Role {
	if x != nil {
		return x.Role
	}
	return NoteINfo_role_unspecified
}

func (x *GetResponce) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetResponce) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateNoteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *wrappers.StringValue  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         *wrappers.StringValue  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteInfo) Reset() {
	*x = UpdateNoteInfo{}
	mi := &file_note_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteInfo) ProtoMessage() {}

func (x *UpdateNoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteInfo.ProtoReflect.Descriptor instead.
func (*UpdateNoteInfo) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNoteInfo) GetName() *wrappers.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateNoteInfo) GetEmail() *wrappers.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *UpdateNoteInfo        `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_note_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetInfo() *UpdateNoteInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_note_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_note_proto protoreflect.FileDescriptor

const file_note_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"note.proto\x12\anote_v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb0\x01\n" +
	"\bNoteINfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12+\n" +
	"\x11password_coonfirm\x18\x04 \x01(\tR\x10passwordCoonfirm\"1\n" +
	"\x04Role\x12\x14\n" +
	"\x10role_unspecified\x10\x00\x12\b\n" +
	"\x04user\x10\x01\x12\t\n" +
	"\x05admin\x10\x02\"\xb3\x01\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x04info\x18\x02 \x01(\v2\x11.note_v1.NoteINfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"6\n" +
	"\rCreateRequest\x12%\n" +
	"\x04info\x18\x01 \x01(\v2\x11.note_v1.NoteINfoR\x04info\" \n" +
	"\x0eCreateResponce\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe9\x01\n" +
	"\vGetResponce\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12*\n" +
	"\x04role\x18\x04 \x01(\x0e2\x16.note_v1.NoteINfo.RoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"v\n" +
	"\x0eUpdateNoteInfo\x120\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x122\n" +
	"\x05email\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\"L\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x04info\x18\x02 \x01(\v2\x17.note_v1.UpdateNoteInfoR\x04info\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xe9\x01\n" +
	"\x06NoteV1\x129\n" +
	"\x06Create\x12\x16.note_v1.CreateRequest\x1a\x17.note_v1.CreateResponce\x120\n" +
	"\x03Get\x12\x13.note_v1.GetRequest\x1a\x14.note_v1.GetResponce\x128\n" +
	"\x06Update\x12\x16.note_v1.UpdateRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x06Delete\x12\x16.note_v1.DeleteRequest\x1a\x16.google.protobuf.EmptyB0Z.github.com/MAPiryazev/Auth/pkg/note_v1;note_v1b\x06proto3"

var (
	file_note_proto_rawDescOnce sync.Once
	file_note_proto_rawDescData []byte
)

func file_note_proto_rawDescGZIP() []byte {
	file_note_proto_rawDescOnce.Do(func() {
		file_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_note_proto_rawDesc), len(file_note_proto_rawDesc)))
	})
	return file_note_proto_rawDescData
}

var file_note_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_note_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_note_proto_goTypes = []any{
	(NoteINfo_Role)(0),           // 0: note_v1.NoteINfo.Role
	(*NoteINfo)(nil),             // 1: note_v1.NoteINfo
	(*Note)(nil),                 // 2: note_v1.Note
	(*CreateRequest)(nil),        // 3: note_v1.CreateRequest
	(*CreateResponce)(nil),       // 4: note_v1.CreateResponce
	(*GetRequest)(nil),           // 5: note_v1.GetRequest
	(*GetResponce)(nil),          // 6: note_v1.GetResponce
	(*UpdateNoteInfo)(nil),       // 7: note_v1.UpdateNoteInfo
	(*UpdateRequest)(nil),        // 8: note_v1.UpdateRequest
	(*DeleteRequest)(nil),        // 9: note_v1.DeleteRequest
	(*timestamp.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*wrappers.StringValue)(nil), // 11: google.protobuf.StringValue
	(*empty.Empty)(nil),          // 12: google.protobuf.Empty
}
var file_note_proto_depIdxs = []int32{
	1,  // 0: note_v1.Note.info:type_name -> note_v1.NoteINfo
	10, // 1: note_v1.Note.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: note_v1.Note.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: note_v1.CreateRequest.info:type_name -> note_v1.NoteINfo
	0,  // 4: note_v1.GetResponce.role:type_name -> note_v1.NoteINfo.Role
	10, // 5: note_v1.GetResponce.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: note_v1.GetResponce.updated_at:type_name -> google.protobuf.Timestamp
	11, // 7: note_v1.UpdateNoteInfo.name:type_name -> google.protobuf.StringValue
	11, // 8: note_v1.UpdateNoteInfo.email:type_name -> google.protobuf.StringValue
	7,  // 9: note_v1.UpdateRequest.info:type_name -> note_v1.UpdateNoteInfo
	3,  // 10: note_v1.NoteV1.Create:input_type -> note_v1.CreateRequest
	5,  // 11: note_v1.NoteV1.Get:input_type -> note_v1.GetRequest
	8,  // 12: note_v1.NoteV1.Update:input_type -> note_v1.UpdateRequest
	9,  // 13: note_v1.NoteV1.Delete:input_type -> note_v1.DeleteRequest
	4,  // 14: note_v1.NoteV1.Create:output_type -> note_v1.CreateResponce
	6,  // 15: note_v1.NoteV1.Get:output_type -> note_v1.GetResponce
	12, // 16: note_v1.NoteV1.Update:output_type -> google.protobuf.Empty
	12, // 17: note_v1.NoteV1.Delete:output_type -> google.protobuf.Empty
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_note_proto_init() }
func file_note_proto_init() {
	if File_note_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_note_proto_rawDesc), len(file_note_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_proto_goTypes,
		DependencyIndexes: file_note_proto_depIdxs,
		EnumInfos:         file_note_proto_enumTypes,
		MessageInfos:      file_note_proto_msgTypes,
	}.Build()
	File_note_proto = out.File
	file_note_proto_goTypes = nil
	file_note_proto_depIdxs = nil
}
